# Generated by Django 3.2 on 2021-04-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(unique=True)),
                ('site', models.CharField(max_length=25)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(blank=True, null=True)),
                ('link', models.CharField(max_length=255, unique=True)),
                ('host_site', models.CharField(max_length=20)),
                ('lowest_price', models.CharField(max_length=25)),
                ('current_price', models.CharField(max_length=25)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('price_last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
