# Generated by Django 3.2 on 2021-04-30 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.link'),
        ),
    ]
