# Generated by Django 3.2 on 2021-04-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
